---
id: sapporogui1403
base_name: gtk-entrance
tags:
- gtk+
- ruby-gnome2
presentation_date: 2014/03/16
version: 2014.3.16.2
licenses:
- CC BY 3.0
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Masafumi Yokoyama
  email: myokoym@gmail.com
  rubygems_user: myokoym
  slideshare_user: myokoym
  speaker_deck_user: myokoym
